#!/usr/bin/env python3
"""Battle background: PNG -> src/battlebg.h (deduped 4bpp tiles + 30x20 map).
Tiles land in charblock 2 (BG2 CBB(1) indices 512+). Palette: 11 colors
into bank 9 entries 4..14 (entries 1-3 stay text colors).
usage: mkbattlebg.py <src.png> <out.h>"""
import sys
from PIL import Image

src, out = sys.argv[1], sys.argv[2]
im = Image.open(src).convert('RGB')
w, h = im.size
if w * 160 > h * 240:
    nw = h * 240 // 160
    im = im.crop(((w - nw) // 2, 0, (w + nw) // 2, h))
else:
    nh = w * 160 // 240
    im = im.crop((0, (h - nh) // 2, w, (h + nh) // 2))
im = im.resize((240, 160), Image.LANCZOS)

q = im.quantize(colors=11, method=Image.MEDIANCUT, dither=Image.NONE)
pal = q.getpalette()[:11 * 3]
pix = q.load()

def rgb15(r, g, b): return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)

tiles = {}      # tuple(8 words) -> index
order = []
tmap = []
for ty in range(20):
    for tx in range(30):
        words = []
        for y in range(8):
            wv = 0
            for x in range(8):
                idx = pix[tx * 8 + x, ty * 8 + y] + 4   # bank entries 4..14
                wv |= idx << (x * 4)
            words.append(wv)
        key = tuple(words)
        if key not in tiles:
            tiles[key] = len(order)
            order.append(key)
        tmap.append(tiles[key])

BASE = 320   # cb1 free region above map patterns; runs into cb2
assert len(order) <= 1024 - BASE, f'{len(order)} unique tiles > {1024-BASE}'
with open(out, 'w') as f:
    f.write('/* generated by tools/mkbattlebg.py — do not edit */\n')
    f.write('#ifndef BATTLEBG_H\n#define BATTLEBG_H\n#include "gba.h"\n\n')
    f.write(f'#define BATTLEBG_NTILES {len(order)}\n')
    f.write(f'#define BATTLEBG_BASE {BASE}\n')
    f.write('#define BATTLEBG_BANK 9\n')
    f.write('static const u16 battlebg_pal[11] = {')
    f.write(','.join(f'0x{rgb15(pal[i*3],pal[i*3+1],pal[i*3+2]):04x}'
                     for i in range(11)))
    f.write('};\n')
    f.write(f'static const u16 battlebg_map[600] = {{\n')
    for i in range(0, 600, 30):
        f.write(','.join(str(v) for v in tmap[i:i+30]) + ',\n')
    f.write('};\n')
    f.write(f'static const u32 battlebg_tiles[{len(order) * 8}] = {{\n')
    for t in order:
        f.write(','.join(f'0x{v:08x}' for v in t) + ',\n')
    f.write('};\n#endif\n')
print(f'mkbattlebg: {len(order)} unique tiles, 11 colors')
