#!/usr/bin/env python3
"""Battle arena backdrop: PNG -> src/battlebg.h (deduped 4bpp tiles + 30x10 map).
Cover-cropped to 3:1 and downscaled to 240x80 — the arena band y16..95 of the
battle screen (rows 2..11). Rows 0-1 and 12-19 stay blank (backdrop color).
Tiles land at BATTLEBG_BASE in the BG2 charspace (above the 5 card-face
slots 176..350). Palette: 11 colors into bank 9 entries 4..14.
usage: mkbattlebg.py <src.png> <out.h>"""
import sys
from PIL import Image

W, H = 240, 80
src, out = sys.argv[1], sys.argv[2]
im = Image.open(src).convert('RGB')
w, h = im.size
if w * H > h * W:
    nw = h * W // H
    im = im.crop(((w - nw) // 2, 0, (w + nw) // 2, h))
else:
    nh = w * H // W
    im = im.crop((0, (h - nh) // 2, w, (h + nh) // 2))
im = im.resize((W, H), Image.LANCZOS)

q = im.quantize(colors=11, method=Image.MEDIANCUT, dither=Image.NONE)
pal = q.getpalette()[:11 * 3]
pix = q.load()

def rgb15(r, g, b): return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)

tiles = {}      # tuple(8 words) -> index
order = []
tmap = []
for ty in range(H // 8):
    for tx in range(W // 8):
        words = []
        for y in range(8):
            wv = 0
            for x in range(8):
                idx = pix[tx * 8 + x, ty * 8 + y] + 4   # bank entries 4..14
                wv |= idx << (x * 4)
            words.append(wv)
        key = tuple(words)
        if key not in tiles:
            tiles[key] = len(order)
            order.append(key)
        tmap.append(tiles[key])

NMAP = (W // 8) * (H // 8)
BASE = 352   # above card faces 176..350; runs into cb2
assert len(order) <= 1024 - BASE, f'{len(order)} unique tiles > {1024-BASE}'
with open(out, 'w') as f:
    f.write('/* generated by tools/mkbattlebg.py — do not edit */\n')
    f.write('#ifndef BATTLEBG_H\n#define BATTLEBG_H\n#include "gba.h"\n\n')
    f.write(f'#define BATTLEBG_NTILES {len(order)}\n')
    f.write(f'#define BATTLEBG_BASE {BASE}\n')
    f.write('#define BATTLEBG_BANK 9\n')
    f.write(f'#define BATTLEBG_ROWS {H // 8}\n')
    f.write('static const u16 battlebg_pal[11] = {')
    f.write(','.join(f'0x{rgb15(pal[i*3],pal[i*3+1],pal[i*3+2]):04x}'
                     for i in range(11)))
    f.write('};\n')
    f.write(f'static const u16 battlebg_map[{NMAP}] = {{\n')
    for i in range(0, NMAP, 30):
        f.write(','.join(str(v) for v in tmap[i:i+30]) + ',\n')
    f.write('};\n')
    f.write(f'static const u32 battlebg_tiles[{len(order) * 8}] = {{\n')
    for t in order:
        f.write(','.join(f'0x{v:08x}' for v in t) + ',\n')
    f.write('};\n#endif\n')
print(f'mkbattlebg: {len(order)} unique tiles, 11 colors')
