#!/usr/bin/env python3
"""8x8 BG tile art -> src/bgtiles.h (4bpp tiles for charblock 1 + palette banks).

bgart.txt format:
  !bank <N> <name>          palette bank N (10..15), then color lines:
  =c R G B                  char c -> next color index (1..15), RGB 0..31
  (chars are shared per-bank; '.' is always color 0 = transparent)

  @tilename <bankN>         8x8 tile using bank N's chars
  8 lines of 8 chars

Output: enum TB_<TILENAME> (tile index in charblock 1), bg_tile_bank[] map,
bgtiles data, bgbank palettes. Icon tiles for charblock 0 use the same file
via '@icon:<name> <bankN>' — they land in a separate icon array loaded at
tile 160+ of charblock 0.
"""
import sys, re

def main():
    src, out = sys.argv[1], sys.argv[2]
    banks = {}       # n -> {char: idx}, colors list
    cur = None
    tiles = []       # (name, bank, rows, is_icon)
    tname = None; trows = []; tbank = 0; ticon = False
    for raw in open(src):
        line = raw.rstrip('\n')
        if not line.strip() or line.lstrip().startswith('#'):
            continue
        if line.startswith('!opaque'):
            # !opaque <bank> R G B : tiles of this bank get index-0 pixels
            # replaced by this backfill color (appended to the palette)
            p = line.split()
            b = banks[int(p[1])]
            b['colors'].append((int(p[2]), int(p[3]), int(p[4])))
            b['backfill'] = len(b['colors'])
        elif line.startswith('!bank'):
            parts = line.split()
            cur = int(parts[1])
            banks[cur] = {'map': {}, 'colors': [], 'backfill': 0}
        elif line.startswith('='):
            m = re.match(r'=(\S)\s+(\d+)\s+(\d+)\s+(\d+)', line)
            b = banks[cur]
            b['colors'].append((int(m.group(2)), int(m.group(3)), int(m.group(4))))
            b['map'][m.group(1)] = len(b['colors'])
        elif line.startswith('@'):
            if tname: tiles.append((tname, tbank, trows, ticon))
            head = line[1:].split()
            tname = head[0]; tbank = int(head[1]); trows = []
            ticon = tname.startswith('icon:')
            if ticon: tname = tname[5:]
        else:
            trows.append(line)
    if tname: tiles.append((tname, tbank, trows, ticon))

    # split 16x16 blocks (name prefix 'big:', 16 rows) into 4 8x8 bg tiles
    # named <NAME> (TL; enum base) + _TR/_BL/_BR, consecutive
    expanded = []
    for name, bank, rows, icon in tiles:
        if name.startswith('big:'):
            n = name[4:]
            rows = [r.ljust(16, '.') for r in rows]
            assert len(rows) == 16, f'{n}: {len(rows)} rows (need 16)'
            quads = [(n, 0, 0), (n + '_tr', 8, 0),
                     (n + '_bl', 0, 8), (n + '_br', 8, 8)]
            for qn, ox, oy in quads:
                expanded.append((qn, bank,
                                 [rows[oy + i][ox:ox + 8] for i in range(8)],
                                 False))
        else:
            expanded.append((name, bank, rows, icon))
    tiles = expanded

    def encode(rows, bank, opaque=False):
        rows = [r.ljust(8, '.') for r in rows]
        assert len(rows) == 8
        bf = banks[bank].get('backfill', 0) if opaque else 0
        words = []
        for y in range(8):
            w = 0
            for x in range(8):
                ch = rows[y][x]
                idx = bf if ch == '.' else banks[bank]['map'][ch]
                w |= idx << (x * 4)
            words.append(w)
        return words

    bgt = [t for t in tiles if not t[3]]
    ict = [t for t in tiles if t[3]]

    with open(out, 'w') as f:
        f.write('/* generated by tools/mkbg.py — do not edit */\n')
        f.write('#ifndef BGTILES_H\n#define BGTILES_H\n#include "gba.h"\n\n')
        f.write('enum {  /* charblock 1 tile indices (tile 0 = blank) */\n')
        for i, (n, b, r, _) in enumerate(bgt):
            f.write(f'    TB_{n.upper()} = {i + 1},\n')
        f.write(f'    N_BGTILES = {len(bgt) + 1}\n}};\n\n')
        f.write('#define ICON_BASE 160  /* charblock 0 */\n')
        f.write('enum {\n')
        for i, (n, b, r, _) in enumerate(ict):
            f.write(f'    TI_{n.upper()} = ICON_BASE + {i},\n')
        f.write(f'    N_ICONS = {len(ict)}\n}};\n\n')
        f.write('static const u8 bg_tile_bank[N_BGTILES] = { 0, ')
        f.write(', '.join(str(b) for _, b, _, _ in bgt))
        f.write(' };\n')
        f.write('static const u8 icon_bank[N_ICONS > 0 ? N_ICONS : 1] = { ')
        f.write(', '.join(str(b) for _, b, _, _ in ict) or '0')
        f.write(' };\n\n')
        f.write('#ifdef BGTILES_DATA  /* define in exactly one TU (engine.c) */\n')
        f.write(f'static const u32 bgtile_px[{max(len(bgt),1) * 8}] = {{\n')
        for n, b, r, _ in bgt:
            f.write('    ' + ','.join(f'0x{w:08x}' for w in encode(r, b, opaque=True)) + f', /* {n} */\n')
        f.write('};\n')
        f.write(f'static const u32 icon_px[{max(len(ict),1) * 8}] = {{\n')
        for n, b, r, _ in ict:
            f.write('    ' + ','.join(f'0x{w:08x}' for w in encode(r, b)) + f', /* {n} */\n')
        f.write('};\n')
        f.write('static const u16 bgbank_pal[6][15] = {  /* banks 10..15 */\n')
        for bn in range(10, 16):
            cols = banks.get(bn, {'colors': []})['colors']
            vals = [(r | (g << 5) | (bl << 10)) for r, g, bl in cols]
            vals += [0] * (15 - len(vals))
            f.write('    {' + ','.join(f'0x{v:04x}' for v in vals) + '},\n')
        f.write('};\n#endif /* BGTILES_DATA */\n\n#endif\n')
    print(f'mkbg: {len(bgt)} bg tiles, {len(ict)} icons, banks {sorted(banks)}')

main()
