#!/usr/bin/env python3
"""assets/cards/<name>.png (40x56 RGBA) -> src/cardimg.h

Full-card faces for the battle hand. Each card is quantized to <=12 colors
(k-means, 5-bit snapped) that live in palette entries 4..15 of a streamed
text bank (banks 0..3 hold the 4 visible hand slots; entries 1..3 stay
text colors). Tiles are 4bpp, 5x7 tiles per card, row-major; pixel value
0 = transparent (rounded corners), else 4..15.
"""
import os, sys
import numpy as np
from PIL import Image

W, H = 40, 56
TW, TH = W // 8, H // 8          # 5 x 7 tiles
NCOL = 12                        # palette entries 4..15

# must match card id enum order in src/cards.h
ORDER = [
    'strike', 'defend', 'bash',
    'anger', 'bodyslam', 'cleave', 'clothesline', 'flex', 'headbutt',
    'heavyblade', 'ironwave', 'pommel', 'shrug', 'thunderclap', 'twinstrike',
    'bloodlet', 'carnage', 'disarm', 'entrench', 'flamebarrier',
    'inflame', 'metallicize', 'shockwave', 'uppercut', 'whirlwind',
    'barricade', 'bludgeon', 'demonform', 'feed', 'immolate',
    'impervious', 'offering',
    'wound', 'burn', 'slimed', 'dazed',
]


def kmeans_pal(pix, k, iters=25, seed=7):
    rng = np.random.default_rng(seed)
    pts = pix.astype(float)
    c = [pts[rng.integers(len(pts))]]
    for _ in range(k - 1):
        d = np.min(((pts[:, None, :] - np.array(c)[None, :, :]) ** 2).sum(2), axis=1)
        c.append(pts[rng.choice(len(pts), p=d / d.sum())])
    c = np.array(c)
    for _ in range(iters):
        lab = ((pts[:, None, :] - c[None, :, :]) ** 2).sum(2).argmin(1)
        for j in range(k):
            m = lab == j
            if m.any():
                c[j] = pts[m].mean(0)
    return np.clip(np.round(c / 8) * 8, 0, 248).astype(int)


def main():
    root = os.path.join(os.path.dirname(__file__), '..')
    adir = os.path.join(root, 'assets', 'cards')
    pals, tiles = [], []
    for name in ORDER:
        fn = os.path.join(adir, name + '.png')
        im = Image.open(fn).convert('RGBA')
        assert im.size == (W, H), f'{name}: {im.size} != {W}x{H}'
        a = np.asarray(im)
        opaque = a[..., 3] >= 128
        pal = kmeans_pal(a[..., :3][opaque], NCOL)
        rgb = a[..., :3].astype(int)
        idx = ((rgb[..., None, :] - pal[None, None, :, :]) ** 2).sum(3).argmin(2) + 4
        idx[~opaque] = 0
        pals.append([(r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10) for r, g, b in pal])
        words = []
        for ty in range(TH):
            for tx in range(TW):
                for y in range(8):
                    w0 = 0
                    for x in range(8):
                        w0 |= int(idx[ty * 8 + y, tx * 8 + x]) << (x * 4)
                    words.append(w0)
        tiles.append(words)

    out = os.path.join(root, 'src', 'cardimg.h')
    with open(out, 'w') as f:
        f.write('/* generated by tools/mkcards.py — do not edit */\n')
        f.write('#ifndef CARDIMG_HDR\n#define CARDIMG_HDR\n\n')
        f.write(f'#define CARDIMG_TW {TW}\n#define CARDIMG_TH {TH}\n')
        f.write(f'#define CARDIMG_TILES {TW * TH}\n')
        f.write(f'#define CARDIMG_NCARDS {len(ORDER)}\n\n')
        f.write(f'static const u16 cardimg_pal[{len(ORDER)}][{NCOL}] = {{\n')
        for p in pals:
            f.write('    {' + ','.join(f'0x{v:04x}' for v in p) + '},\n')
        f.write('};\n\n')
        f.write(f'static const u32 cardimg_tiles[{len(ORDER)}][{TW * TH * 8}] = {{\n')
        for words in tiles:
            f.write('    {\n')
            for i in range(0, len(words), 8):
                f.write('    ' + ','.join(f'0x{w:08x}' for w in words[i:i + 8]) + ',\n')
            f.write('    },\n')
        f.write('};\n\n#endif\n')
    print(f'{out}: {len(ORDER)} cards, {len(ORDER) * TW * TH * 32} tile bytes')


if __name__ == '__main__':
    main()
