#!/usr/bin/env python3
"""Player hero battle sprite: PNG -> 64x64 4bpp GBA OBJ sprite + 15-color palette.

Keys out the baked background (checkerboard / solid) by edge flood-fill, fits the
character to ~CHAR_H px tall, centered with feet at the bottom of a 64x64 canvas
(so it renders at the on-screen size the user liked, not the full 64), nudges
saturation so the red cape survives the 15-color quantize, and emits
src/heroimg.h (hero_tiles[512] = 64 4bpp tiles in 1D layout + hero_pal[15]).

usage: mkhero.py [src.png]
"""
import sys, os
from PIL import Image, ImageDraw, ImageEnhance
import numpy as np

SRC = sys.argv[1] if len(sys.argv) > 1 else \
    '/Users/austinsomer/Downloads/Gemini_Generated_Image_813ve1813ve1813v.png'
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CANVAS = 64
CHAR_H = 52          # target character height inside the 64 canvas (~1.5x on-screen)
BOTTOM_PAD = 1       # px of gap under the feet


def rgb15(r, g, b):
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


im = Image.open(SRC).convert('RGB')
W, H = im.size

# ---- key out background: the baked checkerboard is neutral LIGHT gray
#      (R==G==B, bright); the character's lights are warm (tan/steel), so a
#      global neutral-light removal keys the bg without holing the character. ----
a = np.asarray(im).astype(int)
mx, mn = a.max(2), a.min(2)
bg = (mx - mn < 14) & (mx >= 205)
alpha = np.where(bg, 0, 255).astype(np.uint8)

ys, xs = np.where(alpha > 0)
x0, x1, y0, y1 = xs.min(), xs.max(), ys.min(), ys.max()
rgba = Image.fromarray(np.dstack([np.asarray(im), alpha]), 'RGBA').crop((x0, y0, x1 + 1, y1 + 1))
cw, ch = rgba.size

# ---- scale so the character is CHAR_H tall (fit width too), place feet-bottom ----
scale = min(CHAR_H / ch, (CANVAS - 2) / cw)
nw, nh = max(1, round(cw * scale)), max(1, round(ch * scale))
small = rgba.resize((nw, nh), Image.LANCZOS)
canvas = Image.new('RGBA', (CANVAS, CANVAS), (0, 0, 0, 0))
canvas.paste(small, ((CANVAS - nw) // 2, CANVAS - nh - BOTTOM_PAD), small)

# harden alpha (1-bit): anything the resize made partially transparent -> on/off
arr = np.asarray(canvas).copy()
op = arr[:, :, 3] >= 110
arr[:, :, 3] = np.where(op, 255, 0)

# ---- quantize the opaque pixels to 15 colors (saturation bump keeps the red) ----
rgb = Image.fromarray(arr[:, :, :3], 'RGB')
rgb = ImageEnhance.Color(rgb).enhance(1.35)
q = rgb.quantize(colors=15, method=Image.MAXCOVERAGE, dither=Image.NONE)
pal = q.getpalette()[:15 * 3]
idx = np.asarray(q)                       # 0..14 per pixel
# palette entry 0 = transparent; shift colors to 1..15, transparent pixels -> 0
pix = np.where(op, idx + 1, 0).astype(np.uint8)

# ---- pack into 64x64 4bpp tiles, 1D layout (8x8 grid, row-major), 8 u32/tile ----
tiles = []
for ty in range(8):
    for tx in range(8):
        for py in range(8):
            row = 0
            for px in range(8):
                row |= int(pix[ty * 8 + py, tx * 8 + px]) << (px * 4)
            tiles.append(row)

pal16 = [rgb15(pal[i * 3], pal[i * 3 + 1], pal[i * 3 + 2]) for i in range(15)]

with open(os.path.join(ROOT, 'src', 'heroimg.h'), 'w') as f:
    f.write('/* generated by tools/mkhero.py - do not edit */\n')
    f.write('#ifndef HEROIMG_H\n#define HEROIMG_H\n#include "gba.h"\n\n')
    f.write(f'#define HERO_W 64\n#define HERO_H 64\n')
    f.write(f'#define HERO_CHAR_H {nh}   /* fitted character height in px */\n\n')
    f.write(f'static const u16 hero_pal[15] = {{')
    f.write(','.join(f'0x{c:04x}' for c in pal16))
    f.write('};\n\n')
    f.write(f'static const u32 hero_tiles[{len(tiles)}] = {{\n')
    for i in range(0, len(tiles), 8):
        f.write(','.join(f'0x{t:08x}' for t in tiles[i:i + 8]) + ',\n')
    f.write('};\n\n#endif\n')

print(f'mkhero: char fitted {nw}x{nh} in 64x64, {len(tiles)} u32 tiles, 15 colors -> src/heroimg.h')
