#!/usr/bin/env python3
"""assets/battle-ui/{hud,relics}/*.png -> src/hudimg.h

Battle HUD elements + relic icons. Each SET shares one 12-color k-means
palette (5-bit snapped) living in entries 4..15 of a streamed text bank
(bank 4 = HUD, bank 5 = relics; text/UI only use entries 1..3). Tiles are
4bpp row-major, pixel 0 = transparent, else 4..15. Tiles stream into the
charblock-1 gap below the card faces (63..151, 89 tiles).
"""
import os
import numpy as np
from PIL import Image

HUD = [  # (name, w, h) — enum order H_*
    ('drawpile', 16, 24), ('discardpile', 16, 24), ('energy', 24, 24),
    ('endturn', 32, 24), ('target', 16, 16),
    ('coin', 16, 16), ('atk', 16, 16), ('def', 16, 16),
    ('buff', 16, 16), ('debuff', 16, 16),
]
RELICS = ['burningblood', 'vajra', 'bronzescales', 'anchor',
          'lantern', 'strawberry', 'bagofprep', 'bloodvial']  # relic id order


def kmeans_pal(pix, k=12, iters=25, seed=7):
    rng = np.random.default_rng(seed)
    pts = pix.astype(float)
    c = [pts[rng.integers(len(pts))]]
    for _ in range(k - 1):
        d = np.min(((pts[:, None, :] - np.array(c)[None, :, :]) ** 2).sum(2), axis=1)
        c.append(pts[rng.choice(len(pts), p=d / d.sum())])
    c = np.array(c)
    for _ in range(iters):
        lab = ((pts[:, None, :] - c[None, :, :]) ** 2).sum(2).argmin(1)
        for j in range(k):
            m = lab == j
            if m.any():
                c[j] = pts[m].mean(0)
    return np.clip(np.round(c / 8) * 8, 0, 248).astype(int)


def load_set(dirname, names_dims):
    imgs, allpix = [], []
    for entry in names_dims:
        name, w, h = entry
        fn = os.path.join(ROOT, 'assets', 'battle-ui', dirname, name + '.png')
        im = Image.open(fn).convert('RGBA')
        assert im.size == (w, h), f'{name}: {im.size} != {w}x{h}'
        a = np.asarray(im)
        imgs.append(a)
        allpix.append(a[..., :3][a[..., 3] >= 128])
    pal = kmeans_pal(np.concatenate(allpix))
    tiles_per, words_all = [], []
    for a in imgs:
        opaque = a[..., 3] >= 128
        rgb = a[..., :3].astype(int)
        idx = ((rgb[..., None, :] - pal[None, None, :, :]) ** 2).sum(3).argmin(2) + 4
        idx[~opaque] = 0
        h, w = idx.shape
        words = []
        for ty in range(h // 8):
            for tx in range(w // 8):
                for y in range(8):
                    wv = 0
                    for x in range(8):
                        wv |= int(idx[ty * 8 + y, tx * 8 + x]) << (x * 4)
                    words.append(wv)
        tiles_per.append(len(words) // 8)
        words_all.extend(words)
    pal15 = [(r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10) for r, g, b in pal]
    return pal15, tiles_per, words_all


ROOT = os.path.join(os.path.dirname(__file__), '..')


def emit_words(f, words):
    for i in range(0, len(words), 8):
        f.write(','.join(f'0x{w:08x}' for w in words[i:i + 8]) + ',\n')


def main():
    hpal, htiles, hwords = load_set('hud', HUD)
    rpal, rtiles, rwords = load_set('relics', [(n, 16, 16) for n in RELICS])
    assert all(t == 4 for t in rtiles)
    nhud = sum(htiles)
    out = os.path.join(ROOT, 'src', 'hudimg.h')
    with open(out, 'w') as f:
        f.write('/* generated by tools/mkhud.py — do not edit */\n')
        f.write('#ifndef HUDIMG_H\n#define HUDIMG_H\n\n')
        f.write('enum { H_DRAWPILE, H_DISCARDPILE, H_ENERGY, H_ENDTURN,\n')
        f.write('       H_TARGET, H_COIN, H_ATK, H_DEF, H_BUFF, H_DEBUFF,\n')
        f.write('       N_HUDELEM };\n\n')
        f.write(f'#define HUDIMG_NTILES {nhud}\n')
        f.write(f'#define RELICIMG_NTILES {sum(rtiles)}\n\n')
        f.write('#ifdef HUDIMG_DATA\n')
        f.write('static const struct { u16 ofs; u8 tw, th; } '
                f'hudimg_elem[N_HUDELEM] = {{\n')
        ofs = 0
        for (name, w, h), nt in zip(HUD, htiles):
            f.write(f'    {{{ofs},{w // 8},{h // 8}}}, /* {name} */\n')
            ofs += nt
        f.write('};\n\n')
        f.write('static const u16 hudimg_pal[12] = {')
        f.write(','.join(f'0x{v:04x}' for v in hpal))
        f.write('};\n')
        f.write('static const u16 relicimg_pal[12] = {')
        f.write(','.join(f'0x{v:04x}' for v in rpal))
        f.write('};\n\n')
        f.write(f'static const u32 hudimg_tiles[{len(hwords)}] = {{\n')
        emit_words(f, hwords)
        f.write('};\n\n')
        f.write(f'static const u32 relicimg_tiles[{len(rwords)}] = {{\n')
        emit_words(f, rwords)
        f.write('};\n#endif /* HUDIMG_DATA */\n\n#endif\n')
    print(f'{out}: {nhud} hud tiles + {sum(rtiles)} relic tiles')


if __name__ == '__main__':
    main()
