#!/usr/bin/env python3
"""Full-screen mode-4 title image: PNG -> src/title_img.h
usage: mkimage.py <src.png> <out.h> [overlay text]
Cover-crops to 240x160, optional 2x text overlay near bottom,
quantizes to 255 colors, emits u16 palette + u16-packed pixel data."""
import sys
from PIL import Image, ImageDraw, ImageFont

src, out = sys.argv[1], sys.argv[2]
text = sys.argv[3] if len(sys.argv) > 3 else None

im = Image.open(src).convert('RGB')
# cover-crop to 3:2
w, h = im.size
if w * 160 > h * 240:
    nw = h * 240 // 160
    im = im.crop(((w - nw) // 2, 0, (w + nw) // 2, h))
else:
    nh = w * 160 // 240
    im = im.crop((0, (h - nh) // 2, w, (h + nh) // 2))
im = im.resize((240, 160), Image.LANCZOS)

if text:
    # render with the game's font8x8 at 2x: chunky cream text, black
    # outline, filled arrow cursor before it (StS menu style)
    import re, os
    hdr = open(os.path.join(os.path.dirname(__file__), '..', 'src',
                            'font8x8.h')).read()
    m = re.search(r'font8x8_basic\s*\[128\]\[8\]\s*=\s*\{(.*?)\n\};',
                  hdr, re.S)
    rowvals = [int(v, 16) for v in re.findall(r'0x[0-9A-Fa-f]{2}', m.group(1))]
    font = [rowvals[i*8:(i+1)*8] for i in range(128)]
    ARROW = [0x08, 0x18, 0x38, 0x78, 0x78, 0x38, 0x18, 0x08]

    glyphs = [ARROW, font[ord(' ')]] + [font[ord(c)] for c in text]
    SCALE = 1.5   # ~30% smaller than the old 2x
    G = int(8 * SCALE)
    mask = set()
    arrow_mask = set()
    for gi, g in enumerate(glyphs):
        for sy in range(G):
            for sx in range(G):
                if g[int(sy / SCALE)] & (1 << int(sx / SCALE)):
                    mask.add((gi * G + sx, sy))
                    if gi == 0:
                        arrow_mask.add((gi * G + sx, sy))
    tw, th = len(glyphs) * G, G
    # centered between logo bottom (~y95) and screen bottom
    x0, y0 = (240 - tw) // 2, (95 + 160 - th) // 2
    dst = im.load()
    CREAM, BLACK = (232, 224, 196), (16, 14, 20)
    for (x, y) in mask:
        for dy in (-1, 0, 1):
            for dx in (-1, 0, 1):
                if (x + dx, y + dy) not in mask:
                    xx, yy = x0 + x + dx, y0 + y + dy
                    if 0 <= xx < 240 and 0 <= yy < 160:
                        dst[xx, yy] = BLACK
    for (x, y) in mask:
        dst[x0 + x, y0 + y] = CREAM

q = im.quantize(colors=254, method=Image.MEDIANCUT, dither=Image.FLOYDSTEINBERG)
pal = q.getpalette()[:254 * 3] + [232, 224, 196]  # slot 254: arrow (blinkable)
pix = q.load()
if text:
    for (x, y) in arrow_mask:
        pix[x0 + x, y0 + y] = 254

def rgb15(r, g, b): return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)

with open(out, 'w') as fo:
    fo.write('/* generated by tools/mkimage.py — do not edit */\n')
    fo.write('#ifndef TITLE_IMG_H\n#define TITLE_IMG_H\n#include "gba.h"\n\n')
    fo.write('#define TITLE_ARROW_PALIDX 255\n')
    fo.write(f'#define TITLE_ARROW_ON  0x{rgb15(232,224,196):04x}\n')
    fo.write(f'#define TITLE_ARROW_OFF 0x{rgb15(16,14,20):04x}\n\n')
    fo.write('static const u16 title_pal[256] = {0,')
    fo.write(','.join(f'0x{rgb15(pal[i*3],pal[i*3+1],pal[i*3+2]):04x}'
                      for i in range(255)))
    fo.write('};\n\n')
    words = []
    for y in range(160):
        for x in range(0, 240, 2):
            words.append((pix[x, y] + 1) | ((pix[x + 1, y] + 1) << 8))
    fo.write(f'static const u16 title_px[{len(words)}] = {{\n')
    for i in range(0, len(words), 16):
        fo.write(','.join(f'0x{v:04x}' for v in words[i:i+16]) + ',\n')
    fo.write('};\n\n#endif\n')
print(f'mkimage: 240x160, {len(words)*2} bytes')
