#!/usr/bin/env python3
"""Music tracks -> assets/music/*.pcm (signed 8-bit mono 13379 Hz raw)
plus src/pcmdata.s (.incbin + length symbols for src/pcm.c).

usage: mkpcm.py <title-audio> <run-audio>
       mkpcm.py --run-only <run-audio>    (keep existing title.pcm)
       mkpcm.py --intro <intro-audio>     (one-shot; keep existing title/run)

Per track: decode via ffmpeg, trim silence at both ends, peak-normalize,
crossfade the tail into the head (seamless loop), pad to a multiple of
224 samples (one vblank frame at 13379 Hz; also 16-aligns for DMA).
The intro track is a ONE-SHOT (no loop crossfade; small tail fade so the
hard stop at end-of-track doesn't click) — pcm.c stops it instead of looping.
pcmdata.s always lists every track that exists on disk (title/run/intro).
"""
import os, subprocess, sys
import numpy as np

SR = 13379
FRAME = 224
XFADE = int(SR * 0.6)

root = os.path.join(os.path.dirname(__file__), '..')
outdir = os.path.join(root, 'assets', 'music')
os.makedirs(outdir, exist_ok=True)


def load(fn):
    raw = subprocess.run(
        ['ffmpeg', '-v', 'error', '-i', fn, '-ac', '1', '-ar', str(SR),
         '-f', 's16le', '-'],
        check=True, capture_output=True).stdout
    return np.frombuffer(raw, np.int16).astype(np.float32) / 32768.0


def process(fn, name, loop=True):
    x = load(fn)
    # trim <-48dB ends
    loud = np.where(np.abs(x) > 0.004)[0]
    x = x[loud[0]:loud[-1] + 1]
    x *= 0.92 / max(np.abs(x).max(), 1e-6)
    if loop:
        # fade tail into head so the DMA loop point is seamless
        if len(x) > XFADE * 3:
            t = np.linspace(0, 1, XFADE, dtype=np.float32)
            x[-XFADE:] = x[-XFADE:] * (1 - t) + x[:XFADE] * t
    else:
        # one-shot: brief tail fade so the hard stop at end doesn't click
        fo = min(int(SR * 0.08), len(x))
        x[-fo:] *= np.linspace(1, 0, fo, dtype=np.float32)
    n = (len(x) // FRAME) * FRAME
    x = x[:n]
    s8 = np.clip(np.round(x * 127), -128, 127).astype(np.int8)
    fn8 = os.path.join(outdir, name + '.pcm')
    s8.tofile(fn8)
    print(f'{fn8}: {n} samples = {n/SR:.1f}s, {n//1024}KB {"[loop]" if loop else "[one-shot]"}')
    return n


def disk_len(name):
    return os.path.getsize(os.path.join(outdir, name + '.pcm'))  # 1 byte/sample


def main():
    a = sys.argv[1]
    if a == '--run-only':                       # keep title + intro
        process(sys.argv[2], 'run')
    elif a == '--intro':                        # keep title + run
        process(sys.argv[2], 'intro', loop=False)
    else:                                       # <title> <run>
        process(sys.argv[1], 'title')
        process(sys.argv[2], 'run')
    # emit every track that exists on disk, in fixed order (title, run, intro)
    tracks = [t for t in ('title', 'run', 'intro')
              if os.path.exists(os.path.join(outdir, t + '.pcm'))]
    asm = os.path.join(root, 'src', 'pcmdata.s')
    with open(asm, 'w') as f:
        f.write('@ generated by tools/mkpcm.py — do not edit\n')
        f.write('    .section .rodata\n    .align 2\n')
        for name in tracks:
            f.write(f'    .global pcm_{name}\npcm_{name}:\n')
            f.write(f'    .incbin "assets/music/{name}.pcm"\n')
            f.write(f'    .global pcm_{name}_len\n    .align 2\n')
            f.write(f'pcm_{name}_len: .word {disk_len(name)}\n')
    print(f'{asm} written ({", ".join(tracks)})')


if __name__ == '__main__':
    main()
