#!/usr/bin/env python3
"""Synthesize combat SFX samples -> assets/sfx/*.pcm + src/sfxdata.s

All sounds generated from scratch (numpy): thudding hit, metallic clang,
coin ding, noise slash. 13379 Hz signed 8-bit mono, one-shot, each padded
with 448 zero samples (2 frames) so the frame-counted DMA stop lands in
silence. Lengths multiple of 16 for the 4-word FIFO bursts.
"""
import os
import numpy as np

SR = 13379
root = os.path.join(os.path.dirname(__file__), '..')
outdir = os.path.join(root, 'assets', 'sfx')
os.makedirs(outdir, exist_ok=True)
rng = np.random.default_rng(11)


def env(n, decay):
    return np.exp(-np.arange(n) / (SR * decay))


def t(n):
    return np.arange(n) / SR


def hit():
    n = int(SR * 0.11)
    f = np.linspace(95, 45, n)                       # falling thump
    x = np.sin(2 * np.pi * np.cumsum(f) / SR) * env(n, 0.045) * 0.9
    nb = int(SR * 0.05)
    x[:nb] += rng.standard_normal(nb) * env(nb, 0.012) * 0.55
    return x


def clang():
    n = int(SR * 0.16)
    x = np.zeros(n)
    for f0, a in ((817, 0.5), (1377, 0.35), (2153, 0.25), (3041, 0.15)):
        x += np.sin(2 * np.pi * f0 * t(n)) * env(n, 0.035) * a
    nb = int(SR * 0.012)
    x[:nb] += rng.standard_normal(nb) * 0.6          # strike click
    return x * 0.8


def coin():
    n = int(SR * 0.16)
    x = np.sin(2 * np.pi * 1320 * t(n)) * env(n, 0.05) * 0.5
    n2 = int(SR * 0.10)
    d = np.zeros(n)
    d[n - n2:] = np.sin(2 * np.pi * 1980 * t(n2)) * env(n2, 0.06) * 0.6
    return x + d


def slash():
    n = int(SR * 0.09)
    x = rng.standard_normal(n)
    a = 0.0
    y = np.zeros(n)                                   # 1-pole LP, opening->closing
    for i in range(n):                                # cutoff sweeps down
        k = 0.9 - 0.75 * i / n
        a += k * (x[i] - a)
        y[i] = a
    return y * env(n, 0.05) * 1.4


def emit(name, x):
    x = np.concatenate([x, np.zeros(448)])
    x = np.clip(x, -1, 1)
    n = ((len(x) + 15) // 16) * 16
    x = np.concatenate([x, np.zeros(n - len(x))])
    s8 = np.clip(np.round(x * 120), -128, 127).astype(np.int8)
    s8.tofile(os.path.join(outdir, name + '.pcm'))
    print(f'{name}: {n} samples ({n*1000//SR}ms)')
    return n


def main():
    lens = [(nm, emit(nm, fn())) for nm, fn in
            (('hit', hit), ('clang', clang), ('coin', coin), ('slash', slash))]
    with open(os.path.join(root, 'src', 'sfxdata.s'), 'w') as f:
        f.write('@ generated by tools/mksfx.py — do not edit\n')
        f.write('    .section .rodata\n    .align 2\n')
        for nm, ln in lens:
            f.write(f'    .global sfxpcm_{nm}\nsfxpcm_{nm}:\n')
            f.write(f'    .incbin "assets/sfx/{nm}.pcm"\n')
            f.write(f'    .global sfxpcm_{nm}_len\n    .align 2\n')
            f.write(f'sfxpcm_{nm}_len: .word {ln}\n')
    print('src/sfxdata.s written')


if __name__ == '__main__':
    main()
