#!/usr/bin/env python3
"""Pre-intro splash images -> mode-4 slides for the GBA.

Each image in assets/pre-intro-images/ (sorted) -> cover-crop 240x160 ->
adaptive 256-color quantize -> assets/slides/slides.bin (per slide: 256 x u16
BGR555 palette then 240x160 byte indices) + src/slidesdata.s (.incbin) +
src/slidesimg.h (count + frame geometry). Played by slides_play() in intro.c:
fade from black, hold 2s, fade to black, per slide, before the intro video.
"""
import os, glob
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'src')
IMGDIR = os.path.join(ROOT, 'assets', 'pre-intro-images')
W, H = 240, 160

files = sorted(glob.glob(os.path.join(IMGDIR, '*.png')))
assert files, 'no images in ' + IMGDIR


def rgb15(r, g, b):
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


def cover_crop(im):
    w, h = im.size
    if w * H > h * W:                     # too wide: crop sides
        nw = h * W // H
        im = im.crop(((w - nw) // 2, 0, (w + nw) // 2, h))
    else:                                 # too tall: crop top/bottom
        nh = w * H // W
        im = im.crop((0, (h - nh) // 2, w, (h + nh) // 2))
    return im.resize((W, H), Image.LANCZOS)


os.makedirs(os.path.join(ROOT, 'assets', 'slides'), exist_ok=True)
binpath = os.path.join(ROOT, 'assets', 'slides', 'slides.bin')
with open(binpath, 'wb') as bf:
    for fn in files:
        im = cover_crop(Image.open(fn).convert('RGB'))
        q = im.quantize(colors=256, method=Image.MEDIANCUT,
                        dither=Image.FLOYDSTEINBERG)
        pal = q.getpalette()[:256 * 3]
        pal16 = [rgb15(pal[i * 3], pal[i * 3 + 1], pal[i * 3 + 2])
                 for i in range(256)]
        for v in pal16:
            bf.write(bytes((v & 0xff, (v >> 8) & 0xff)))
        px = q.load()
        row = bytearray(W)
        for y in range(H):
            for x in range(W):
                row[x] = px[x, y]
            bf.write(row)

with open(os.path.join(SRC, 'slidesdata.s'), 'w') as f:
    f.write('@ generated by tools/mkslides.py - do not edit\n')
    f.write('    .section .rodata\n    .align 2\n')
    f.write('    .global slides_data\nslides_data:\n')
    f.write('    .incbin "assets/slides/slides.bin"\n')

with open(os.path.join(SRC, 'slidesimg.h'), 'w') as f:
    f.write('/* generated by tools/mkslides.py - do not edit */\n')
    f.write('#ifndef SLIDESIMG_H\n#define SLIDESIMG_H\n#include "gba.h"\n\n')
    f.write(f'#define SLIDES_N {len(files)}\n')
    f.write(f'#define SLIDE_W {W}\n#define SLIDE_H {H}\n')
    f.write('#define SLIDE_PAL_BYTES 512\n')
    f.write(f'#define SLIDE_PIX_BYTES {W * H}\n')
    f.write(f'#define SLIDE_FRAME_BYTES {512 + W * H}\n')
    f.write('extern const unsigned char slides_data[];\n\n#endif\n')

print(f'mkslides: {len(files)} slides -> {os.path.getsize(binpath)} bytes '
      f'({os.path.getsize(binpath)//1024}KB)')
