#!/usr/bin/env python3
"""ASCII pixel art -> src/sprites.h (GBA 4bpp OBJ tiles, 1D mapping).

art.txt format, per sprite:
  @name
  =c R G B     (palette entry, RGB 0..31; chars map to indices 1..15 in order)
  32 lines of 32 chars ('.' = transparent)
"""
import sys, re

def main():
    src, out = sys.argv[1], sys.argv[2]
    sprites = []   # (name, palette[(char,r,g,b)...], rows[32])
    name, pal, rows = None, [], []
    for raw in open(src):
        line = raw.rstrip('\n')
        if not line.strip() or line.lstrip().startswith('#'):
            continue
        if line.startswith('@'):
            if name: sprites.append((name, pal, rows))
            name, pal, rows = line[1:].strip(), [], []
        elif line.startswith('='):
            m = re.match(r'=(\S)\s+(\d+)\s+(\d+)\s+(\d+)', line)
            pal.append((m.group(1), int(m.group(2)), int(m.group(3)), int(m.group(4))))
        else:
            rows.append(line)
    if name: sprites.append((name, pal, rows))

    tiles_out = []   # u32 words
    defs = []
    banks = []       # list of color lists (rgb15), packed <= 15 each
    bank_of = []     # per sprite: (bank index, {char: color idx})
    for name, pal, rows in sprites:
        assert len(rows) == 32, f'{name}: {len(rows)} rows'
        rows = [r.ljust(32, '.') for r in rows]
        colors = [(r | (g << 5) | (b << 10)) for _, r, g, b in pal]
        # pack: find a bank that can absorb this sprite's colors
        chosen = None
        for bi, bc in enumerate(banks):
            merged = list(bc)
            ok = True
            idxmap = {}
            for (ch, *_), col in zip(pal, colors):
                if col in merged:
                    idxmap[ch] = merged.index(col) + 1
                elif len(merged) < 15:
                    merged.append(col)
                    idxmap[ch] = len(merged)
                else:
                    ok = False
                    break
            if ok:
                banks[bi] = merged
                chosen = (bi, idxmap)
                break
        if chosen is None:
            assert len(banks) < 16, 'more than 16 obj palette banks'
            banks.append(list(colors))
            chosen = (len(banks) - 1,
                      {ch: i + 1 for i, (ch, *_ ) in enumerate(pal)})
        bank_of.append(chosen)
        bi, cmap = chosen
        tile_ofs = len(tiles_out) // 8  # 8 u32 words per 4bpp tile
        for ty in range(4):
            for tx in range(4):
                for y in range(8):
                    w = 0
                    for x in range(8):
                        ch = rows[ty * 8 + y][tx * 8 + x]
                        idx = 0 if ch == '.' else cmap[ch]
                        w |= idx << (x * 4)
                    tiles_out.append(w)
        defs.append((name, tile_ofs))
    pals = [bc + [0] * (15 - len(bc)) for bc in banks]

    with open(out, 'w') as f:
        f.write('/* generated by tools/mksprites.py — do not edit */\n')
        f.write('#ifndef SPRITES_H\n#define SPRITES_H\n#include "gba.h"\n\n')
        f.write('enum {\n')
        for i, (name, _) in enumerate(defs):
            f.write(f'    SPR_{name.upper()} = {i},\n')
        f.write(f'    N_SPRITES = {len(defs)}\n}};\n\n')
        f.write('#ifdef SPRITES_DATA  /* define in exactly one TU (engine.c) */\n')
        f.write(f'static const u16 sprite_tile_ofs[N_SPRITES] = {{ ')
        f.write(', '.join(str(t) for _, t in defs))
        f.write(' };\n\n')
        f.write(f'#define N_SPRITE_BANKS {len(pals)}\n')
        f.write('static const u8 sprite_pal_bank[N_SPRITES] = { ')
        f.write(', '.join(str(b) for b, _ in bank_of))
        f.write(' };\n')
        f.write(f'static const u16 sprite_pals[N_SPRITE_BANKS][15] = {{\n')
        for colors in pals:
            f.write('    {' + ','.join(f'0x{c:04x}' for c in colors) + '},\n')
        f.write('};\n\n')
        f.write(f'static const u32 sprite_tiles[{len(tiles_out)}] = {{\n')
        for i in range(0, len(tiles_out), 8):
            f.write('    ' + ','.join(f'0x{w:08x}' for w in tiles_out[i:i+8]) + ',\n')
        f.write('};\n#endif /* SPRITES_DATA */\n\n#endif\n')
    print(f'mksprites: {len(defs)} sprites, {len(tiles_out)*4} bytes tiles')

main()
