#!/usr/bin/env python3
"""Intro video -> mode-4 frame stream for the GBA.

mp4 -> ffmpeg frames (15fps, cover-crop 240x160) -> per-frame adaptive-palette
quantize -> assets/intro/intro.bin  (per frame: 256 x u16 BGR555 palette then
240x160 byte indices) + src/introdata.s (.incbin) + src/introimg.h (counts +
the "PRESS START" text patch baked in the title font for the held final frame).

usage: mkvideo.py [mp4] [nframes_to_keep]
The tail of the source has the game's own baked "PRESS START" text; we keep only
the first nframes (default 116 = up to the fully-assembled scene, before that
text fades in) and overlay our own flashing PRESS START at runtime instead.
"""
import sys, os, subprocess, glob, re
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'src')
MP4 = sys.argv[1] if len(sys.argv) > 1 else '/Users/austinsomer/Downloads/sts-intro.mp4'
NKEEP = int(sys.argv[2]) if len(sys.argv) > 2 else 116
FPS, W, H = 15, 240, 160
TMP = '/tmp/mkvideo_frames'


def rgb15(r, g, b):
    return (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)


# ---- 1) extract frames -------------------------------------------------------
os.makedirs(TMP, exist_ok=True)
for f in glob.glob(os.path.join(TMP, '*.png')):
    os.remove(f)
subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', MP4, '-vf',
                f'fps={FPS},scale={W}:{H}:force_original_aspect_ratio=increase,'
                f'crop={W}:{H}', os.path.join(TMP, 'f%03d.png')], check=True)
files = sorted(glob.glob(os.path.join(TMP, 'f*.png')))[:NKEEP]
N = len(files)

# ---- 2) bake "PRESS START" in the title font (font8x8 @1.5x, black outline) --
SCALE, PAD = 1.5, 1
G = int(8 * SCALE)                         # 12px glyph cell (matches title menu)
FILL_IDX, OUTLINE_IDX = 254, 255
hdr = open(os.path.join(SRC, 'font8x8.h')).read()
m = re.search(r'font8x8_basic\s*\[128\]\[8\]\s*=\s*\{(.*?)\n\};', hdr, re.S)
rowvals = [int(v, 16) for v in re.findall(r'0x[0-9A-Fa-f]{2}', m.group(1))]
font = [rowvals[i * 8:(i + 1) * 8] for i in range(128)]

text = "PRESS START"
glyphs = [font[ord(c)] for c in text]
mask = set()
for gi, g in enumerate(glyphs):
    for sy in range(G):
        for sx in range(G):
            if g[int(sy / SCALE)] & (1 << int(sx / SCALE)):
                mask.add((gi * G + sx, sy))
pw, ph = len(glyphs) * G + 2 * PAD, G + 2 * PAD
patch = bytearray(pw * ph)                 # 0 = transparent
for (x, y) in mask:                        # black outline (dilation) first
    for dy in (-1, 0, 1):
        for dx in (-1, 0, 1):
            if (x + dx, y + dy) not in mask:
                patch[(y + dy + PAD) * pw + (x + dx + PAD)] = OUTLINE_IDX
for (x, y) in mask:                        # fill on top
    patch[(y + PAD) * pw + (x + PAD)] = FILL_IDX
PS_X = (W - pw) // 2
PS_Y = 138                                 # bottom-center (matches source layout)

# ---- 3) quantize frames -> intro.bin ----------------------------------------
os.makedirs(os.path.join(ROOT, 'assets', 'intro'), exist_ok=True)
binpath = os.path.join(ROOT, 'assets', 'intro', 'intro.bin')
with open(binpath, 'wb') as bf:
    for idx, fn in enumerate(files):
        im = Image.open(fn).convert('RGB')
        held = (idx == N - 1)              # last kept frame carries the text slots
        ncol = 254 if held else 256
        q = im.quantize(colors=ncol, method=Image.MEDIANCUT,
                        dither=Image.FLOYDSTEINBERG)
        pal = q.getpalette()[:ncol * 3]
        pal16 = [rgb15(pal[i * 3], pal[i * 3 + 1], pal[i * 3 + 2])
                 for i in range(ncol)]
        while len(pal16) < 256:
            pal16.append(0)
        if held:
            pal16[FILL_IDX] = rgb15(230, 225, 205)     # cream-white text
            pal16[OUTLINE_IDX] = rgb15(16, 14, 20)     # near-black outline
        for v in pal16:
            bf.write(bytes((v & 0xff, (v >> 8) & 0xff)))
        px = q.load()
        row = bytearray(W)
        for y in range(H):
            for x in range(W):
                row[x] = px[x, y]
            bf.write(row)

# ---- 4) emit .s + .h ---------------------------------------------------------
with open(os.path.join(SRC, 'introdata.s'), 'w') as f:
    f.write('@ generated by tools/mkvideo.py - do not edit\n')
    f.write('    .section .rodata\n    .align 2\n')
    f.write('    .global intro_data\nintro_data:\n')
    f.write('    .incbin "assets/intro/intro.bin"\n')

with open(os.path.join(SRC, 'introimg.h'), 'w') as f:
    f.write('/* generated by tools/mkvideo.py - do not edit */\n')
    f.write('#ifndef INTROIMG_H\n#define INTROIMG_H\n#include "gba.h"\n\n')
    f.write(f'#define INTRO_NFRAMES {N}\n')
    f.write(f'#define INTRO_W {W}\n#define INTRO_H {H}\n')
    f.write('#define INTRO_PAL_BYTES 512\n')
    f.write(f'#define INTRO_PIX_BYTES {W * H}\n')
    f.write(f'#define INTRO_FRAME_BYTES {512 + W * H}\n')
    f.write(f'#define INTRO_PS_W {pw}\n#define INTRO_PS_H {ph}\n')
    f.write(f'#define INTRO_PS_X {PS_X}\n#define INTRO_PS_Y {PS_Y}\n')
    f.write(f'#define INTRO_PS_FILL {FILL_IDX}\n')
    f.write(f'#define INTRO_PS_OUTLINE {OUTLINE_IDX}\n')
    f.write('extern const unsigned char intro_data[];\n\n')
    f.write(f'static const unsigned char intro_ps_patch[{len(patch)}] = {{\n')
    for i in range(0, len(patch), 24):
        f.write(','.join(str(b) for b in patch[i:i + 24]) + ',\n')
    f.write('};\n\n#endif\n')

print(f'mkvideo: {N} frames, {os.path.getsize(binpath)} bytes '
      f'({os.path.getsize(binpath)//1024}KB); PS patch {pw}x{ph} at ({PS_X},{PS_Y})')
