@ generated by tools/mkpcm.py — do not edit
    .section .rodata
    .align 2
    .global pcm_title
pcm_title:
    .incbin "assets/music/title.pcm"
    .global pcm_title_len
    .align 2
pcm_title_len: .word 1762656
    .global pcm_run
pcm_run:
    .incbin "assets/music/run.pcm"
    .global pcm_run_len
    .align 2
pcm_run_len: .word 2999360
    .global pcm_intro
pcm_intro:
    .incbin "assets/music/intro.pcm"
    .global pcm_intro_len
    .align 2
pcm_intro_len: .word 284032
