@ generated by tools/mksfx.py — do not edit
    .section .rodata
    .align 2
    .global sfxpcm_hit
sfxpcm_hit:
    .incbin "assets/sfx/hit.pcm"
    .global sfxpcm_hit_len
    .align 2
sfxpcm_hit_len: .word 1920
    .global sfxpcm_clang
sfxpcm_clang:
    .incbin "assets/sfx/clang.pcm"
    .global sfxpcm_clang_len
    .align 2
sfxpcm_clang_len: .word 2592
    .global sfxpcm_coin
sfxpcm_coin:
    .incbin "assets/sfx/coin.pcm"
    .global sfxpcm_coin_len
    .align 2
sfxpcm_coin_len: .word 2592
    .global sfxpcm_slash
sfxpcm_slash:
    .incbin "assets/sfx/slash.pcm"
    .global sfxpcm_slash_len
    .align 2
sfxpcm_slash_len: .word 1664
