/* generated by tools/mkslides.py - do not edit */
#ifndef SLIDESIMG_H
#define SLIDESIMG_H
#include "gba.h"

#define SLIDES_N 2
#define SLIDE_W 240
#define SLIDE_H 160
#define SLIDE_PAL_BYTES 512
#define SLIDE_PIX_BYTES 38400
#define SLIDE_FRAME_BYTES 38912
extern const unsigned char slides_data[];

#endif
